/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rn
 */
public class MainForm extends javax.swing.JFrame {
    private KontrolovacPravopisu kontrolovacPravopisu = new KontrolovacPravopisu();
    
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        KontrolaPravopisuSwingWorker kontrolaPravopisuSwingWorker =
                new KontrolaPravopisuSwingWorker(txtTextovePole, lblKontrolaPravopisu);
        kontrolaPravopisuSwingWorker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextovePole = new javax.swing.JTextArea();
        lblKontrolaPravopisu = new javax.swing.JLabel();
        btnSkontrolujPravopis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTextovePole.setColumns(20);
        txtTextovePole.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        txtTextovePole.setRows(5);
        jScrollPane1.setViewportView(txtTextovePole);

        lblKontrolaPravopisu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblKontrolaPravopisu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnSkontrolujPravopis.setText("Kontrolovať pravopis...");
        btnSkontrolujPravopis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkontrolujPravopisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(lblKontrolaPravopisu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSkontrolujPravopis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKontrolaPravopisu)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSkontrolujPravopis))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkontrolujPravopisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkontrolujPravopisActionPerformed
        for(int i = 0; i < 100000; i++) {
            System.out.println(i);
        }
    }//GEN-LAST:event_btnSkontrolujPravopisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkontrolujPravopis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKontrolaPravopisu;
    private javax.swing.JTextArea txtTextovePole;
    // End of variables declaration//GEN-END:variables
}
